import { msg } from '@lingui/core/macro';

// Lingui extraction only. Strings match DB-seeded command menu labels/shortLabels
// (including literal ${...} placeholders) so resolve-time translateStandardLabel works.
export const getStandardCommandMenuItemLabels = () => [
  msg`Navigate to next \${capitalize(objectMetadataItem.labelSingular)}`,
  msg`Navigate to previous \${capitalize(objectMetadataItem.labelSingular)}`,
  msg`Create new \${capitalize(objectMetadataItem.labelSingular)}`,
  msg`New \${capitalize(objectMetadataItem.labelSingular)}`,
  msg`Delete \${capitalize(objectMetadataLabel)}`,
  msg`Delete`,
  msg`Restore \${capitalize(objectMetadataLabel)}`,
  msg`Restore`,
  msg`Permanently destroy \${capitalize(objectMetadataLabel)}`,
  msg`Destroy`,
  msg`Add to Favorites`,
  msg`Remove from Favorites`,
  msg`Export to PDF`,
  msg`Export`,
  msg`Export \${capitalize(objectMetadataLabel)}`,
  msg`Update \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Update`,
  msg`Merge \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Merge`,
  msg`Import \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Import`,
  msg`Export View`,
  msg`See deleted \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Deleted \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Create View`,
  msg`Hide deleted \${capitalize(objectMetadataItem.labelPlural)}`,
  msg`Hide deleted`,
  msg`Edit Layout`,
  msg`Edit Dashboard`,
  msg`Edit`,
  msg`Save Dashboard`,
  msg`Save`,
  msg`Cancel Edition`,
  msg`Cancel`,
  msg`Duplicate Dashboard`,
  msg`Duplicate`,
  msg`Activate Workflow`,
  msg`Activate`,
  msg`Deactivate Workflow`,
  msg`Deactivate`,
  msg`Discard Draft`,
  msg`Test Workflow`,
  msg`Test`,
  msg`See Active Version`,
  msg`See Runs`,
  msg`See Versions History`,
  msg`See Versions`,
  msg`Add a Node`,
  msg`Tidy up Workflow`,
  msg`Tidy up`,
  msg`Duplicate Workflow`,
  msg`See Version`,
  msg`See Workflow`,
  msg`Stop`,
  msg`Retry`,
  msg`Use as Draft`,
  msg`Search`,
  msg`Ask AI`,
  msg`View Previous AI Chats`,
  msg`Previous AI Chats`,
  msg`Reply`,
  msg`Compose Email`,
  msg`Compose`,
  msg`Compose Campaign`,
  msg`Campaign`,
  msg`Go to Settings`,
  msg`Settings`,
  msg`Go to Experience Settings`,
  msg`Experience`,
  msg`Go to Accounts Settings`,
  msg`Accounts`,
  msg`Go to Emails Settings`,
  msg`Emails`,
  msg`Go to Calendars Settings`,
  msg`Calendars`,
  msg`Go to General Settings`,
  msg`General`,
  msg`Go to Data Model Settings`,
  msg`Data Model`,
  msg`Go to Members Settings`,
  msg`Members`,
  msg`Go to Roles Settings`,
  msg`Roles`,
  msg`Go to Domains Settings`,
  msg`Domains`,
  msg`Go to Billing Settings`,
  msg`Billing`,
  msg`Go to APIs & Webhooks Settings`,
  msg`APIs & Webhooks`,
  msg`Go to Apps Settings`,
  msg`Apps`,
  msg`Go to AI Settings`,
  msg`AI`,
  msg`Go to Security Settings`,
  msg`Security`,
  msg`Go to Admin Panel Settings`,
  msg`Admin Panel`,
  msg`Go to Community Settings`,
  msg`Community`,
  msg`Send Email`,
  msg`Go to \${navigateToObjectMetadataItem.labelPlural}`,
  msg`\${navigateToObjectMetadataItem.labelPlural}`,
  msg`Quick Lead`,
];
